---
name: Node.js CI with Gulp
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 21.x
          - 22.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Run Frontend Build via Gulp
        working-directory: ./backend
        run: npx gulp build:frontend
      - name: Run Linter
        working-directory: ./backend
        run: npx gulp lint:backend
      - name: Upload Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ matrix.node-version }}
          path: frontend/.next/
